Repository bigbio/ibaqpy, pull requests merged in 2025-02, with the labels that each got.

#91 Added cli option for batch correction
  .gitignore
  ibaqpy/commands/correct_batches.py
  ibaqpy/ibaq/ibaqpy_commons.py
  ibaqpy/ibaq/ibaqpy_postprocessing.py
  ibaqpy/ibaqpyc.py
  requirements.txt
  tests/test_batch_correction.py
Labels: Review effort [1-5]: 4

#94 Added support for anndata
  ibaqpy/commands/correct_batches.py
  ibaqpy/ibaq/file_utils.py
  ibaqpy/ibaq/ibaqpy_postprocessing.py
  requirements.txt
  tests/test_batch_correction.py
  tests/test_file_utils.py
  tests/test_ibaqpy_postprocessing.py
Labels: Review effort [1-5]: 4

#96 added logging output and description
  ibaqpy/commands/correct_batches.py
  ibaqpy/ibaq/file_utils.py
Labels: Review effort [1-5]: 2

#99 Polish CLI
  ibaqpy/commands/correct_batches.py
  ibaqpy/commands/features2peptides.py
  ibaqpy/commands/peptides2protein.py
  ibaqpy/ibaq/file_utils.py
  ibaqpy/ibaq/ibaqpy_commons.py
  ibaqpy/ibaq/ibaqpy_postprocessing.py
  ibaqpy/ibaq/peptide_normalization.py
  ibaqpy/ibaq/utils.py
  ibaqpy/ibaqpyc.py
Labels: Review effort [1-5]: 3
